=== PCGen/pcgen/pcgen/system/npcgen/options/options.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2007 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="race">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="choice" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="npcgen_options">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="align" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="race" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="gender" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="class" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="level" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="game_mode" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="level">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="choice"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="gender">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="choice" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="choice" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="choice">
		<xs:complexType>
			<xs:attribute name="weight" type="xs:integer" use="optional" default="1"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="align">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="choice" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== PCGen/pcgen/system/npcgen/options/options35.xml
<?xml version="1.0" encoding="UTF-8"?>
<npcgen_options game_mode="35e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="options.xsd">
	<align name="Any">
		<choice value="*"/>
	</align>
	<align name="Any Good">
		<choice value="LG"/>
		<choice value="NG"/>
		<choice value="CG"/>
	</align>
	<align name="Any Non-Evil">
		<choice value="LG"/>
		<choice value="LN"/>
		<choice value="NG"/>
		<choice value="TN"/>
		<choice value="CG"/>
		<choice value="CN"/>
	</align>
	<align name="Any Neutral">
		<choice value="LN"/>
		<choice value="TN"/>
		<choice value="CN"/>
	</align>
	<align name="Any Non-Good">
		<choice value="LN"/>
		<choice value="LE"/>
		<choice value="TN"/>
		<choice value="NE"/>
		<choice value="CN"/>
		<choice value="CE"/>
	</align>
	<align name="Any Evil">
		<choice value="LE"/>
		<choice value="NE"/>
		<choice value="CE"/>
	</align>
	<align name="Any Non-Lawful">
		<choice value="NE"/>
		<choice value="TN"/>
		<choice value="NE"/>
		<choice value="CG"/>
		<choice value="CN"/>
		<choice value="CE"/>
	</align>
	<align name="Any Non-Chaotic">
		<choice value="LG"/>
		<choice value="LN"/>
		<choice value="LE"/>
		<choice value="NG"/>
		<choice value="TN"/>
		<choice value="NE"/>
	</align>
	<align name="Any Lawful">
		<choice value="LG"/>
		<choice value="LN"/>
		<choice value="LE"/>
	</align>
	<align name="Any (Weighted)">
		<choice value="LG" weight="20"/>
		<choice value="NG" weight="20"/>
		<choice value="CG" weight="20"/>
		<choice value="LN" weight="50"/>
		<choice value="TN" weight="50"/>
		<choice value="CN" weight="50"/>
		<choice value="LE" weight="30"/>
		<choice value="NE" weight="30"/>
		<choice value="CE" weight="30"/>
	</align>
	<align name="Lawful Good">
		<choice value="LG"/>
	</align>
	<align name="Lawful Neutral">
		<choice value="LN"/>
	</align>
	<align name="Lawful Evil">
		<choice value="LE"/>
	</align>
	<align name="Neutral Good">
		<choice value="NG"/>
	</align>
	<align name="Neutral">
		<choice value="TN"/>
	</align>
	<align name="Neutral Evil">
		<choice value="NE"/>
	</align>
	<align name="Chaotic Good">
		<choice value="CG"/>
	</align>
	<align name="Chaotic Neutral">
		<choice value="CN"/>
	</align>
	<align name="Chaotic Evil">
		<choice value="CE"/>
	</align>
	<race name="Any">
		<choice value="*"/>
	</race>
	<race name="Any Core">
		<choice value="Human"/>
		<choice value="Dwarf"/>
		<choice value="Elf"/>
		<choice value="Gnome"/>
		<choice value="Half-Elf"/>
		<choice value="Half-orc"/>
		<choice value="Halfling"/>
	</race>
	<race name="Any Humanoid">
		<choice value="TYPE=Humanoid"/>
	</race>
	<gender name="Any">
		<choice value="*"/>
	</gender>
	<gender name="Humanoid">
		<choice value="Male"/>
		<choice value="Female"/>
	</gender>
	<gender name="Humanoid (Weighted)">
		<choice value="Male" weight="2"/>
		<choice value="Female" weight="1"/>
	</gender>
	<class name="Any">
		<choice value="*"/>
	</class>
	<class name="Any PC">
		<choice value="TYPE=Base.PC"/>
	</class>
	<class name="Any NPC">
		<choice value="TYPE=Base.NPC"/>
	</class>
	<class name="Any PC (Weighted)">
		<choice value="Barbarian" weight="5"/>
		<choice value="Bard" weight="9"/>
		<choice value="Cleric" weight="15"/>
		<choice value="Druid" weight="4"/>
		<choice value="Fighter" weight="24"/>
		<choice value="Monk" weight="4"/>
		<choice value="Paladin" weight="2"/>
		<choice value="Ranger" weight="2"/>
		<choice value="Rogue" weight="15"/>
		<choice value="Sorcerer" weight="6"/>
		<choice value="Wizard" weight="11"/>
		<choice value="TYPE=Base.PC" weight="1"/>
	</class>
	<level name="Any (1-20)">
		<choice value="1,20"/>
	</level>
	<level name="Low (1-5)">
		<choice value="1,5"/>
	</level>
	<level name="Medium (6-10)">
		<choice value="6,10"/>
	</level>
	<level name="High (11-15)">
		<choice value="11,15"/>
	</level>
	<level name="Very High (16-20)">
		<choice value="16,20"/>
	</level>
	<level name="Epic">
		<choice value="21,40"/>
	</level>
</npcgen_options>
