=== PCGen/pcgen/pcgen/plugins/Encounter/encounter.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lookuptable (row+)>
<!ELEMENT row (item+)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT item (loc+)>
<!ATTLIST lookuptable
	name CDATA #REQUIRED
>

<!ELEMENT loc (#PCDATA)>
<!ATTLIST loc
	language CDATA #REQUIRED
	comment CDATA #IMPLIED
>

=== PCGen/pcgen/plugins/Encounter/encounter_tables/environments.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lookuptable SYSTEM "../encounter.dtd" >
<lookuptable name="Environments">
	<!-- Header -->
	<row>
		<item>Environment</item>
		<item>File</item>
	</row>  
	        
	<row>
		<!-- Environment -->
		<item>Level 1 Dungeon<loc language="fr">Donjon niveau 1</loc></item>
		<!-- File -->
		<item>[environments/dungeon1]<loc language="fr">[environnements/donjon1]</loc></item>
	</row>  
	<row>
		<!-- Environment -->
		<item>Level 2 Dungeon<loc language="fr">Donjon niveau 2</loc></item>
		<!-- File -->
		<item>[environments/dungeon2]</item>
	</row>  


</lookuptable>

=== PCGen/pcgen/plugins/Encounter/encounter_tables/environments/dungeon2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lookuptable SYSTEM "../../encounter.dtd" >
<lookuptable name="Dingy Dungeon level 2">
	<!-- Header -->
	<row>
		<item>d%</item>
		<item>Number</item>
		<item>Monster</item>
	</row>
	
	<!-- 01-30% -->
	<row>
		<item>30</item>
		<item>1d4</item>
		<item>Ettercap</item>
	</row>
	<!-- 31-54% -->
	<row>
		<item>54</item>
		<item>2d3</item>
		<item>Orc</item>
	</row>
	<!-- 55-70% -->
	<row>
		<item>70</item>
		<item>1</item>
		<item>Ogre</item>
	</row>
	<!-- 71-100% -->
	<row>
		<item>100</item>
		<item>1d3</item>
		<item>Lizard (Giant)</item>
	</row>
		

</lookuptable>

=== PCGen/pcgen/plugins/Encounter/encounter_tables/4_14.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lookuptable SYSTEM "../encounter.dtd" >
<lookuptable name="table 4-14 Modified Die Roll">
	<!-- Multiplier -->
	<row>
		<item>die roll</item>
		<item>1/3</item>
		<item>1/2</item>
		<item>2/3</item>
		<item>3/2</item>
		<item>2</item>
		<item>3</item>
		<item>4</item>
	</row>
	
	<!-- Die roll 1 -->
	<row>
		<item>1</item>
		<item>1</item>
		<item>1</item>
		<item>1</item>
		<item>1d2</item>
		<item>1d3</item>
		<item>1d3+1</item>
		<item>1d4+2</item>
	</row>	

	<!-- Die roll 1d2 -->
	<row>
		<item>1d2</item>
		<item>1</item>
		<item>1</item>
		<item>1</item>
		<item>1d3</item>
		<item>1d3+1</item>
		<item>1d4+2</item>
		<item>1d6+3</item>
	</row>	
	
	<!-- Die roll 1d3 -->
	<row>
		<item>1d3</item>
		<item>1</item>
		<item>1</item>
		<item>1d2</item>
		<item>1d3+1</item>
		<item>1d4+2</item>
		<item>1d6+3</item>
		<item>1d6+5</item>
	</row>	
	
	<!-- Die roll 1d3+1 -->
	<row>
		<item>1d3+1</item>
		<item>1</item>
		<item>1d2</item>
		<item>1d3</item>
		<item>1d4+2</item>
		<item>1d6+3</item>
		<item>1d6+5</item>
		<item>1d4+10</item>
	</row>		

	<!-- Die roll 1d4+2 -->
	<row>
		<item>1d4+2</item>
		<item>1d2</item>
		<item>1d3</item>
		<item>1d3+1</item>
		<item>1d6+3</item>
		<item>1d6+5</item>
		<item>1d4+10</item>
		<item>Table 4-14</item>
	</row>	

	<!-- Die roll 1d6+3 -->
	<row>
		<item>1d6+3</item>
		<item>1d3</item>
		<item>1d3+1</item>
		<item>1d4+2</item>
		<item>1d6+5</item>
		<item>1d4+10</item>
		<item>Table 4-14</item>
		<item>Table 4-14</item>
	</row>	

	<!-- Die roll 1d6+5 -->
	<row>
		<item>1d6+5</item>
		<item>1d3+1</item>
		<item>1d4+2</item>
		<item>1d6+3</item>
		<item>1dd4+10</item>
		<item>Table 4-14</item>
		<item>Table 4-14</item>
		<item>Table 4-14</item>
	</row>	
</lookuptable>

=== PCGen/pcgen/pcgen/plugins/Encounter/encounter_tables/environments/dungeon1.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lookuptable SYSTEM "../../encounter.dtd" >
<lookuptable name="Dingy Dungeon level 1">
	<!-- Header -->
	<row>
		<item>d%</item>
		<item>Number</item>
		<item>Monster</item>
	</row>
	
	<!-- 01-30% -->
	<row>
		<item>30</item>
		<item>2d4</item>
		<item>Kobold</item>
	</row>
	<!-- 31-54% -->
	<row>
		<item>54</item>
		<item>1d3</item>
		<item>Orc</item>
	</row>
	<!-- 55-70% -->
	<row>
		<item>70</item>
		<item>2d3</item>
		<item>Goblin</item>
	</row>
	<!-- 71-100% -->
	<row>
		<item>100</item>
		<item>1d3</item>
		<item>Lizard</item>
	</row>
		

</lookuptable>

=== PCGen/pcgen/plugins/Encounter/encounter_tables/4_15.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lookuptable SYSTEM "../encounter.dtd" >
<lookuptable name="table 4-15 1st-Level Dungeon Encounters">
	<!-- header -->
	<row>
		<item>d%</item>
		<item>Role</item>
		<item>Number of Creatures and kind</item>
		<item>Treasure</item>
	</row>
	
	<!-- 01-04% -->
	<row>
		<item>4</item>
		<item>Critter</item>
		<item>1d3 centipedes, Medium-size monstrous (vermin)</item>
		<item>20%</item>
	</row>	

	<!-- 05-09% -->
	<row>
		<item>9</item>
		<item>Critter</item>
		<item>1d3+1 dire rats</item>
		<item>20%</item>
	</row>	

	<!-- 10-14% -->
	<row>
		<item>14</item>
		<item>Critter</item>
		<item>1d3+1 fire beetles, giant (vermin)</item>
		<item>20%</item>
	</row>	

	<!-- 15-17% -->
	<row>
		<item>17</item>
		<item>Critter</item>
		<item>1d3 scorpions, small monstrous (vermin)</item>
		<item>20%</item>
	</row>	

	<!-- 18-20% -->
	<row>
		<item>20</item>
		<item>Critter</item>
		<item>1d3 spiders, small monstrous (vermin)</item>
		<item>20%</item>
	</row>	

	<!-- 21-25% -->
	<row>
		<item>25</item>
		<item>Dragon</item>
		<item>1 dragon, [Table 4-35]</item>
		<item>80%+2</item>
	</row>	

	<!-- 26-30% -->
	<row>
		<item>30</item>
		<item>Friend</item>
		<item>1d3 dwarven warriors</item>
		<item>80%+1</item>
	</row>	

	<!-- 31-35% -->
	<row>
		<item>35</item>
		<item>Friend</item>
		<item>1d3 elven warriors</item>
		<item>80%+1</item>
	</row>	
	
	<!-- 36-40% -->
	<row>
		<item>40</item>
		<item>NPC</item>
		<item>1 1st-level NPC</item>
		<item>Gear</item>
	</row>	
	
	<!-- 41-45% -->
	<row>
		<item>45</item>
		<item>Terror</item>
		<item>1 darkmantle</item>
		<item>50%+1</item>
	</row>	
	
	<!-- 46-55% -->
	<row>
		<item>55</item>
		<item>Terror</item>
		<item>1 krenshar</item>
		<item>50%+1</item>
	</row>		
	
	<!-- 56-60% -->
	<row>
		<item>60</item>
		<item>Terror</item>
		<item>1 lemure (devil)</item>
		<item>50%+1</item>
	</row>	
	
	<!-- 61-65% -->
	<row>
		<item>65</item>
		<item>Tough</item>
		<item>1d4+2 goblins</item>
		<item>80%+1</item>
	</row>	
	
	<!-- 66-70% -->
	<row>
		<item>70</item>
		<item>Tough</item>
		<item>1 hobgoblin + 1d3 goblins</item>
		<item>80%+1</item>
	</row>	
	
	<!-- 71-80% -->
	<row>
		<item>80</item>
		<item>Tough</item>
		<item>1d6+3 kobolds</item>
		<item>80%+1</item>
	</row>	
	
	<!-- 81-90% -->
	<row>
		<item>90</item>
		<item>Undead</item>
		<item>1d3+1 skeletons, medium-size</item>
		<item>50%</item>
	</row>	
	
	<!-- 91-100% -->
	<row>
		<item>100</item>
		<item>Undead</item>
		<item>1d3 zombies, medium-size</item>
		<item>50%</item>
	</row>	
</lookuptable>
