=== PCGen/pcgen/plugins/Overland Travel/travel_methods/travel_methods.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : travel_methods.dtd
    Created on : July 28, 2003, 12:55 PM
    Author     : Juliean Galak
    Description:
        DTD for a document holding travel methods and associated speeds
-->

<!ELEMENT table (item*)>
<!ELEMENT item (name, speed)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT speed (#PCDATA)>

=== PCGen/pcgen/plugins/Overland Travel/travel_methods/travel_methods.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TRMETHOD SYSTEM "travel_methods.dtd">
<!--
    Document   : travel_methods.xml
    Created on : July 28, 2003, 1:08 PM
    Author     : Juliean Galak
    Description:
        Stores travel method data
-->

<table>
    <item>
        <name>Walk (15')</name>
        <speed>12</speed>
    </item>
    <item>
        <name>Walk (20')</name>
        <speed>16</speed>
    </item>
    <item>
        <name>Walk (30')</name>
        <speed>24</speed>
    </item>
    <item>
        <name>Walk (40')</name>
        <speed>32</speed>
    </item>
    <item>
        <name>Cart or Wagon</name>
        <speed>16</speed>
    </item>
</table>
