=== PCGen/pcgen/pcgen/plugins/Experience/experience.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lookuptable (row+)>
<!ELEMENT row (item+)>
<!ELEMENT item (#PCDATA)>
<!ATTLIST lookuptable
	name CDATA #REQUIRED
>

=== PCGen/pcgen/plugins/Experience/experience_tables/7_1.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lookuptable SYSTEM "../experience.dtd" >
<lookuptable name="table 7-1 Experience Point Awards">
<!-- Challenge Rating -->
	<row>
		<item>Party Level</item>
		<item>1</item>
		<item>2</item>
		<item>3</item>
		<item>4</item>
		<item>5</item>
		<item>6</item>
		<item>7</item>
		<item>8</item>
		<item>9</item>
		<item>10</item>
		<item>11</item>
		<item>12</item>
		<item>13</item>
		<item>14</item>
		<item>15</item>
		<item>16</item>
		<item>17</item>
		<item>18</item>
		<item>19</item>
		<item>20</item>
		<item>21</item>
		<item>22</item>
		<item>23</item>
		<item>24</item>
		<item>25</item>
		<item>26</item>
		<item>27</item>
		<item>28</item>
		<item>29</item>
		<item>30</item>
		<item>31</item>
		<item>32</item>
		<item>33</item>
		<item>34</item>
		<item>35</item>
		<item>36</item>
		<item>37</item>
		<item>38</item>
		<item>39</item>
		<item>40</item>
		<item>41</item>
		<item>42</item>
		<item>43</item>
		<item>44</item>
		<item>45</item>
		<item>46</item>
		<item>47</item>
		<item>48</item>
		<item>49</item>
		<item>50</item>
		<item>51</item>
		<item>52</item>
		<item>53</item>
		<item>54</item>
		<item>55</item>
		<item>56</item>
		<item>57</item>
		<item>58</item>
		<item>59</item>
		<item>60</item>
		<item>61</item>
		<item>62</item>
		<item>63</item>
		<item>64</item>
		<item>65</item>
		<item>66</item>
		<item>67</item>
		<item>68</item>
		<item>69</item>
		<item>70</item>
		<item>71</item>
		<item>72</item>
		<item>73</item>
		<item>74</item>
		<item>75</item>
		<item>76</item>
		<item>77</item>
		<item>78</item>
		<item>79</item>
		<item>80</item>
		<item>81</item>
		<item>82</item>
		<item>83</item>
		<item>84</item>
		<item>85</item>
		<item>86</item>
		<item>87</item>
		<item>88</item>
		<item>89</item>
		<item>90</item>
		<item>91</item>
		<item>92</item>
		<item>93</item>
		<item>94</item>
		<item>95</item>
		<item>96</item>
		<item>97</item>
		<item>98</item>
		<item>99</item>
		<item>100</item>
	</row>

<!-- Level 1-3 -->
	<row>
		<item>1</item>
		<item>300</item>
		<item>600</item>
		<item>900</item>
		<item>1350</item>
		<item>1800</item>
		<item>2700</item>
		<item>3600</item>
		<item>5400</item>
		<item>7200</item>
		<item>10800</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 21-30 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 31-40 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 41-50 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 51-60 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 61-70 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 71-80 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 81-90 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 91-100 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
	</row>

<!-- Level 1-3 -->
	<row>
		<item>2</item>
		<item>300</item>
		<item>600</item>
		<item>900</item>
		<item>1350</item>
		<item>1800</item>
		<item>2700</item>
		<item>3600</item>
		<item>5400</item>
		<item>7200</item>
		<item>10800</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 21-30 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 31-40 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 41-50 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 51-60 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 61-70 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 71-80 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 81-90 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 91-100 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
	</row>

<!-- Level 1-3 -->
	<row>
		<item>3</item>
		<item>300</item>
		<item>600</item>
		<item>900</item>
		<item>1350</item>
		<item>1800</item>
		<item>2700</item>
		<item>3600</item>
		<item>5400</item>
		<item>7200</item>
		<item>10800</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 21-30 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 31-40 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 41-50 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 51-60 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 61-70 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 71-80 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 81-90 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 91-100 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
	</row>

<!-- Level 4 -->
	<row>
		<item>4</item>
		<item>300</item>
		<item>600</item>
		<item>800</item>
		<item>1200</item>
		<item>1600</item>
		<item>2400</item>
		<item>3200</item>
		<item>4800</item>
		<item>6400</item>
		<item>9600</item>
		<item>12800</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 21-30 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 31-40 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 41-50 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 51-60 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 61-70 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 71-80 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 81-90 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>

      <!-- CR 91-100 -->
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
		<item>0</item>
	</row>

<!-- Level 5 -->
	<row>
		<item>5</item>
		<item>300</item>
