=== PCGen/pcgen/pcgen/system/npcgen/treasure/treasure.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="entry">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="equipment" maxOccurs="unbounded"/>
				<xs:element ref="eqmod" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="weight" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="eqmod">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string"/>
			<xs:attribute name="link" type="xs:string"/>
			<xs:attribute name="pre" type="xs:string"/>
			<xs:attribute name="roll" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="eqmod_table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="entry" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="eqmod" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="link" type="xs:string"/>
			<xs:attribute name="value" type="xs:string"/>
			<xs:attribute name="choose" type="xs:string"/>
			<xs:attribute name="quantity" type="xs:string"/>
			<xs:attribute name="rolls" type="xs:string"/>
			<xs:attribute name="size" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipment_tables">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="table"/>
				<xs:element ref="eqmod_table"/>
			</xs:choice>
			<xs:attribute name="game_mode" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="entry" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== PCGen/pcgen/system/npcgen/treasure/rand_treas_rings35.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipment_tables game_mode="35e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="treasure.xsd">
	<table id="MIN_RINGS" name="Minor Rings">
		<entry weight="18" name="Protection +1">
			<equipment value="Ring (Protection +1)" />
		</entry>
		<entry weight="18" name="Feather falling">
			<equipment value="Ring (Feather Falling)" />
		</entry>
		<entry weight="8" name="Sustenance">
			<equipment value="Ring (Sustenance)" />
		</entry>
		<entry weight="8" name="Climbing">
			<equipment value="Ring of Climbing" />
		</entry>
		<entry weight="8" name="Jumping">
			<equipment value="Ring (Jumping)" />
		</entry>
		<entry weight="8" name="Swimming">
			<equipment value="Ring (Swimming)" />
		</entry>
		<entry weight="10" name="Counterspells">
			<equipment value="Ring of Counterspells" />
		</entry>
		<entry weight="5" name="Mind shielding">
			<equipment value="Ring (Mind Shielding)" />
		</entry>
		<entry weight="5" name="Protection +2">
			<equipment value="Ring (Protection +2)" />
		</entry>
		<entry weight="5" name="Force shield">
			<equipment value="Ring (Force Shield)" />
		</entry>
		<entry weight="5" name="Ram">
			<equipment value="Ring (Ram)" />
		</entry>
		<entry weight="3" name="Animal friendship">
			<equipment value="Ring of Animal Friendship" />
		</entry>
		<entry weight="3" name="Energy resistance, minor">
			<equipment choose="Acid|Cold|Electricity|Fire|Sonic" value="Ring (Energy Resistance/%CHOICE/Minor)" />
		</entry>
		<entry weight="2" name="Chameleon power">
			<equipment value="Ring of Chameleon Power" />
		</entry>
		<entry weight="2" name="Water walking">
			<equipment value="Ring (Water Walking)" />
		</entry>
	</table>
	<table id="MED_RINGS" name="Medium Rings">
		<entry weight="5" name="Counterspells">
			<equipment value="Ring of Counterspells" />
		</entry>
		<entry weight="3" name="Mind shielding">
			<equipment value="Ring (Mind Shielding)" />
		</entry>
		<entry weight="10" name="Protection +2">
			<equipment value="Ring (Protection +2)" />
		</entry>
		<entry weight="5" name="Force shield">
			<equipment value="Ring (Force Shield)" />
		</entry>
		<entry weight="5" name="Ram">
			<equipment value="Ring (Ram)" />
		</entry>
		<entry weight="6" name="Climbing, improved">
			<equipment value="Ring of Climbing (Improved)" />
		</entry>
<!-- Missing from the SRD
		<entry weight="6" name="Jumping, improved">
			<equipment value="Ring (Jumping/Improved)" />
		</entry>
-->
		<entry weight="6" name="Swimming, improved">
			<equipment value="Ring (Swimming/Improved)" />
		</entry>
		<entry weight="5" name="Animal friendship">
			<equipment value="Ring of Animal Friendship" />
		</entry>
		<entry weight="7" name="Energy resistance, minor">
			<equipment choose="Acid|Cold|Electricity|Fire|Sonic" value="Ring (Energy Resistance/%CHOICE/Minor)" />
		</entry>
		<entry weight="5" name="Chameleon power">
			<equipment value="Ring of Chameleon Power" />
		</entry>
		<entry weight="5" name="Water walking">
			<equipment value="Ring (Water Walking)" />
		</entry>
		<entry weight="5" name="Protection +3">
			<equipment value="Ring (Protection +3)" />
		</entry>
		<entry weight="5" name="Spell storing, minor">
			<equipment value="Ring (Spell Storing/Minor)" />
		</entry>
		<entry weight="5" name="Invisibility">
			<equipment value="Ring (Invisibility)" />
		</entry>
		<entry weight="5" name="Wizardry (I)">
			<equipment value="Ring (Wizardry I)" />
		</entry>
		<entry weight="5" name="Evasion">
			<equipment value="Ring (Evasion)" />
		</entry>
		<entry weight="3" name="X-ray vision">
			<equipment value="Ring (X-Ray Vision)" />
		</entry>
		<entry weight="4" name="Blinking">
			<equipment value="Ring of Blinking" />
		</entry>
		<entry weight="3" name="Energy resistance, major">
			<equipment choose="Acid|Cold|Electricity|Fire|Sonic" value="Ring (Energy Resistance/%CHOICE/Major)" />
		</entry>
	</table>
	<table id="MAJ_RINGS" name="Major Rings">
		<entry weight="2" name="Energy resistance, minor">
			<equipment choose="Acid|Cold|Electricity|Fire|Sonic" value="Ring (Energy Resistance/%CHOICE/Minor)" />
		</entry>
		<entry weight="5" name="Protection +3">
			<equipment value="Ring (Protection +3)" />
		</entry>
		<entry weight="3" name="Spell storing, minor">
			<equipment value="Ring (Spell Storing/Minor)" />
		</entry>
		<entry weight="5" name="Invisibility">
			<equipment value="Ring (Invisibility)" />
		</entry>
		<entry weight="4" name="Wizardry (I)">
			<equipment value="Ring (Wizardry I)" />
		</entry>
		<entry weight="6" name="Evasion">
			<equipment value="Ring (Evasion)" />
		</entry>
		<entry weight="3" name="X-ray vision">
			<equipment value="Ring (X-Ray Vision)" />
		</entry>
		<entry weight="4" name="Blinking">
			<equipment value="Ring of Blinking" />
		</entry>
		<entry weight="7" name="Energy resistance, major">
			<equipment choose="Acid|Cold|Electricity|Fire|Sonic" value="Ring (Energy Resistance/%CHOICE/Major)" />
		</entry>
		<entry weight="10" name="Protection +4">
			<equipment value="Ring (Protection +4)" />
		</entry>
		<entry weight="6" name="Wizardry (II)">
			<equipment value="Ring (Wizardry II)" />
		</entry>
		<entry weight="5" name="Freedom of movement">
			<equipment value="Ring (Freedom of Movement)" />
		</entry>
		<entry weight="3" name="Energy resistance, greater">
			<equipment choose="Acid|Cold|Electricity|Fire|Sonic" value="Ring (Energy Resistance/%CHOICE/Greater)" />
		</entry>
		<entry weight="2" name="Friend shield (pair)">
			<equipment value="Ring (Friend Shield)" />
		</entry>
		<entry weight="5" name="Protection +5">
			<equipment value="Ring (Protection +5)" />
		</entry>
		<entry weight="4" name="Shooting stars">
			<equipment value="Ring (Shooting Stars)" />
		</entry>
		<entry weight="4" name="Spell storing">
			<equipment value="Ring (Spell Storing)" />
		</entry>
		<entry weight="4" name="Wizardry (III)">
			<equipment value="Ring (Wizardry III)" />
		</entry>
		<entry weight="3" name="Telekinesis">
			<equipment value="Ring (Telekinesis)" />
		</entry>
		<entry weight="2" name="Regeneration">
			<equipment value="Ring (Regeneration)" />
		</entry>
		<entry weight="1" name="Three wishes">
			<equipment value="Ring (Three Wishes)" />
		</entry>
		<entry weight="3" name="Spell turning">
			<equipment value="Ring (Spell Turning)" />
		</entry>
		<entry weight="2" name="Wizardry (IV)">
			<equipment value="Ring (Wizardry IV)" />
		</entry>
		<entry weight="1" name="Djinni calling">
			<equipment value="Ring of Djinni Calling" />
		</entry>
		<entry weight="1" name="Elemental command (air)">
			<equipment value="Ring (Elemental Command/Air)" />
		</entry>
		<entry weight="1" name="Elemental command (earth)">
			<equipment value="Ring (Elemental Command/Earth)" />
		</entry>
		<entry weight="1" name="Elemental command (fire)">
			<equipment value="Ring (Elemental Command/Fire)" />
		</entry>
		<entry weight="1" name="Elemental command (water)">
			<equipment value="Ring (Elemental Command/Water)" />
		</entry>
		<entry weight="1" name="Spell storing, major">
			<equipment value="Ring (Spell Storing/Major)" />
		</entry>
	</table>
</equipment_tables>
